package com.wd44.drivingschoolsystem.Controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
//    @Autowired // This means to get the bean called userRepository
//    // Which is auto-generated by Spring, we will use it to handle the data
//    private UserRepository userRepository;
//
//    @PostMapping(path="/add") // Map ONLY POST Requests
//    public @ResponseBody String addNewUser (@RequestParam String name
//            , @RequestParam String email) {
//        // @ResponseBody means the returned String is the response, not a view name
//        // @RequestParam means it is a parameter from the GET or POST request
//
//        User n = new User();
//        n.setName(name);
//        n.setEmail(email);
//        userRepository.save(n);
//        return "Saved";
//    }
//
//    @GetMapping(path="/all")
//    public @ResponseBody Iterable<User> getAllUsers() {
//        // This returns a JSON or XML with the users
//        return userRepository.findAll();
//    }

//    @Autowired
//    private StudentRepository studentRepository;
//
//    @PostMapping(path="/add")
//    public @ResponseBody String addNewStudent (@RequestParam String name
//            , @RequestParam String email) {
//        Student n = new Student();
//        n.setFullName(name);
//        n.setEmail(email);
//        studentRepository.save(n);
//        return "Saved";
//    }
//
//    @GetMapping(path="/all")
//    public @ResponseBody Iterable<Student> getAllStudents() {
//        return studentRepository.findAll();
//    }
//
//    @Autowired
//    private InstructorRepository instructorRepository;
//
//    @PostMapping(path="/add")
//    public @ResponseBody String addNewInstructor (@RequestParam String name
//            , @RequestParam String email) {
//        Instructor n = new Instructor();
//        n.setFullName(name);
//        n.setEmail(email);
//        instructorRepository.save(n);
//        return "Saved";
//    }
//
//    @GetMapping(path="/all")
//    public @ResponseBody Iterable<Instructor> getAllInstructors() {
//        return instructorRepository.findAll();
//    }
}