-- Mock data seed for local UI testing (H2)
-- This script is executed on application startup via spring.sql.init.*

-- Ensure Progress table exists (older local DB files may not have it yet)
CREATE TABLE IF NOT EXISTS PROGRESS (
    PROGRESSID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    STUDENT_ID INTEGER,
    TOTAL_LESSONS INTEGER,
    COMPLETED_LESSONS INTEGER,
    PENDING_LESSONS INTEGER,
    PROGRESS_PERCENTAGE INTEGER,
    LAST_UPDATED DATE,
    CONSTRAINT FK_PROGRESS_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID)
);

SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE LESSON RESTART IDENTITY;
TRUNCATE TABLE PAYMENT RESTART IDENTITY;
TRUNCATE TABLE PROGRESS RESTART IDENTITY;
TRUNCATE TABLE STUDENT RESTART IDENTITY;
TRUNCATE TABLE INSTRUCTOR RESTART IDENTITY;
TRUNCATE TABLE AUTH_ENTITY RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;

-- AUTH_ENTITY passwords (bcrypt):
-- - admin / admin123
-- - instructor1,instructor2 / instructor123
-- - student1,student2 / password123
-- - lakaa / 12345
INSERT INTO AUTH_ENTITY (ID, EMAIL, ENCRYPTEDPW, USER_TYPE, USERNAME) VALUES
    (1, 'admin@dss.local',       '$2a$10$FgGce0CxLYsztKMLgNELm.QZAX0/Fv2vV7TAJAk8eZRs1vN32YQie', 'ADMIN',      'admin'),
    (2, 'instructor1@dss.local', '$2a$10$ZAiAGo7NBgp1LYcufgBRJunwV5nTlu0nHfijog16i06sUhT46LW5W', 'INSTRUCTOR', 'instructor1'),
    (3, 'instructor2@dss.local', '$2a$10$ZAiAGo7NBgp1LYcufgBRJunwV5nTlu0nHfijog16i06sUhT46LW5W', 'INSTRUCTOR', 'instructor2'),
    (4, 'student1@dss.local',    '$2a$10$1gP02D7DtBC4HE1u3yC5d.d6GyIVMYtnVD9GakVN4XPdp3.Nd38l.', 'STUDENT',    'student1'),
    (5, 'student2@dss.local',    '$2a$10$1gP02D7DtBC4HE1u3yC5d.d6GyIVMYtnVD9GakVN4XPdp3.Nd38l.', 'STUDENT',    'student2'),
    (6, 'lakshan@gmail.com',     '$2a$10$htqO6MRtnqThwiVqEf7yye3fyiPR9WhuH4.AlAEgcPvF9xSNC1AaK', 'STUDENT',    'lakaa');

-- Instructors
INSERT INTO INSTRUCTOR (ID, "Full Name", "Date of Birth", "Phone Number", AUTH_ID) VALUES
    (1, 'Suresh Fernando',  DATE '1985-04-12', '0771111111', 2),
    (2, 'Ashan Jayasinghe', DATE '1988-11-03', '0772222222', 3);

-- Students
INSERT INTO STUDENT (ID, "Full Name", "Date of Birth", "Phone Number", AUTH_ID) VALUES
    (1, 'Kamal Perera',   DATE '2000-02-15', '0773333333', 4),
    (2, 'Nimali Silva',   DATE '1999-08-05', '0774444444', 5),
    (3, 'Lakshan Wijesinghe', DATE '2000-05-19', '0704175230', 6);

-- Lessons
-- Vehicle Type ordinal: 0 = LIGHT, 1 = HEAVY
-- Grade: NULL means "ungraded / pending"
INSERT INTO LESSON (LESSONID, STUDENTID, INSTRUCTORID, "Lesson Date", "Vehicle Type", GRADE, FEEDBACK) VALUES
    (1, 1, 1, DATE '2026-04-01', 0, 'A', 'Great vehicle control and posture.'),
    (2, 1, 1, DATE '2026-04-08', 0, 'B', 'Good turns; practice smoother braking.'),
    (3, 1, 2, DATE '2026-04-15', 0, NULL, NULL),
    (4, 1, 2, DATE '2026-04-22', 0, NULL, NULL),
    (5, 2, 1, DATE '2026-04-03', 1, 'C', 'Needs more mirror checks and lane discipline.'),
    (6, 2, 1, DATE '2026-04-10', 1, 'B', 'Improved awareness; keep practicing hill start.'),
    (7, 2, 2, DATE '2026-04-17', 1, NULL, NULL),
    (8, 2, 2, DATE '2026-04-24', 1, NULL, NULL),

    -- Student 1 extra lessons (mix graded/ungraded)
    (9, 1, 2, DATE '2026-05-01', 0, 'A', 'Confident steering; good lane positioning.'),
    (10, 1, 2, DATE '2026-05-08', 0, NULL, NULL),

    -- Student 2 extra lessons (more graded to vary progress)
    (11, 2, 1, DATE '2026-05-02', 1, 'A', 'Excellent improvement; consistent mirror checks.'),
    (12, 2, 2, DATE '2026-05-09', 1, 'B', 'Good overall; practice smoother clutch control.'),

    -- Student 3 (Lakshan) lessons
    (13, 3, 1, DATE '2026-04-05', 0, 'D', 'Needs work on road signs and gap judgement.'),
    (14, 3, 1, DATE '2026-04-12', 0, 'C', 'Better awareness; continue practicing turning.'),
    (15, 3, 2, DATE '2026-04-19', 0, NULL, NULL),
    (16, 3, 2, DATE '2026-04-26', 0, NULL, NULL);

-- Progress snapshots (consistent with seeded lessons above)
-- Completed = lessons with non-null grade; Pending = total - completed
INSERT INTO PROGRESS (PROGRESSID, STUDENT_ID, TOTAL_LESSONS, COMPLETED_LESSONS, PENDING_LESSONS, PROGRESS_PERCENTAGE, LAST_UPDATED) VALUES
    (1, 1, 6, 3, 3, 50, DATE '2026-05-08'),
    (2, 2, 6, 4, 2, 66, DATE '2026-05-09'),
    (3, 3, 4, 2, 2, 50, DATE '2026-04-26');

-- Keep identity/auto-increment in sync after inserting explicit IDs
ALTER TABLE AUTH_ENTITY ALTER COLUMN ID RESTART WITH 7;
ALTER TABLE STUDENT ALTER COLUMN ID RESTART WITH 4;
ALTER TABLE INSTRUCTOR ALTER COLUMN ID RESTART WITH 3;
ALTER TABLE LESSON ALTER COLUMN LESSONID RESTART WITH 17;
ALTER TABLE PROGRESS ALTER COLUMN PROGRESSID RESTART WITH 4;
